# application name
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhanggongyuan/configTest.git
          username: changeme
          password: changeme
          

# server monitor port
server:
  port: 8181
